services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-ai-backend
    env_file:
      - path: .env
        required: false
    environment:
      DATABASE_URL: sqlite:///./data/sqllite.db
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-ai-frontend
    depends_on:
      - backend
    ports:
      - "80:80"